# Generated by Django 6.0.7 on 2026-07-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('General Checkup', 'General Checkup'), ('Dental Care', 'Dental Care'), ('Cardiology', 'Cardiology'), ('Laboratory Test', 'Laboratory Test'), ('Emergency Care', 'Emergency Care'), ('Pediatrics', 'Pediatrics')], max_length=100),
        ),
    ]
