# Generated by Django 6.0.7 on 2026-07-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanoapp', '0002_alter_appointment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('General Checkup', 'General Checkup'), ('senior homecare', 'senior homecare'), ('medicalconsultation', 'medicalconsultation'), ('tubechanges', 'tubechanges'), ('woundcare', 'woundcare'), ('chronicdisease', 'chronicdisease')], max_length=100),
        ),
    ]
