# Generated by Django 6.0.7 on 2026-07-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanoapp', '0003_alter_appointment_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('General Checkup', 'General Checkup'), ('senior homecare', 'Senior Homecare'), ('medicalconsultation', 'Medical Consultation'), ('tubechanges', 'Tube Changes'), ('woundcare', 'Wound Care'), ('chronicdisease', 'Chronic Disease')], max_length=100),
        ),
    ]
