# Generated by Django 6.0.7 on 2026-07-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanoapp', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
