# Generated by Django 6.0.7 on 2026-07-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanoapp', '0007_appointment_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('service', models.CharField(choices=[('Senior Homecare', 'Senior Homecare'), ('Medical Consultation', 'Medical Consultation'), ('Tube Changes (NGT, Catheter)', 'Tube Changes (NGT, Catheter)'), ('Wound Care', 'Wound Care'), ('Chronic Disease Followup', 'Chronic Disease Followup')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
