# Generated by Django 6.0.7 on 2026-07-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanoapp', '0008_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
